name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet: [ '2.1.300', '4.5' ]
        
    steps:
    - uses: actions/checkout@v1
    - name: Install .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Build
    - run: dotnet build --configuration Release
    - name: Test
    - run: dotnet test --no-build
